name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip
        pip install --upgrade pip
        pip install buildozer cython

    - name: Accept Android Licenses
      run: |
        mkdir -p ~/.android
        echo 'count=0' > ~/.android/repositories.cfg
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Set API and Build Tools
      run: |
        sed -i 's/^# *android.api =.*/android.api = 33/' buildozer.spec
        sed -i 's/^# *android.build_tools_version =.*/android.build_tools_version = 33.0.2/' buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LifeLearnApp-APK
        path: bin/*.apk
